In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd


In [2]:
X = np.array([ 3,  5,  6,  4, 11, 11, 10, 13, 15, 16, 20, 24, 27, 25, 30, 33, 36,
       37, 36, 41, 42, 42, 47, 49, 50, 48, 50, 55, 59, 60, 59, 64, 64, 67,
       70, 71, 71, 76, 76, 81, 84, 81, 83, 89, 90, 89, 90, 93, 99, 96])

In [3]:
X

array([ 3,  5,  6,  4, 11, 11, 10, 13, 15, 16, 20, 24, 27, 25, 30, 33, 36,
       37, 36, 41, 42, 42, 47, 49, 50, 48, 50, 55, 59, 60, 59, 64, 64, 67,
       70, 71, 71, 76, 76, 81, 84, 81, 83, 89, 90, 89, 90, 93, 99, 96])

In [4]:
Y = 1 + 2* X +np.array([ 3,  3,  5,  8, 10, 14, 11, 15, 18, 20, 23, 22, 27, 25, 30, 29, 36,
       34, 36, 42, 38, 40, 48, 49, 50, 54, 56, 56, 55, 62, 64, 64, 66, 64,
       71, 73, 70, 76, 74, 76, 82, 81, 87, 90, 87, 92, 95, 95, 96, 98])

In [5]:
Y

array([ 10,  14,  18,  17,  33,  37,  32,  42,  49,  53,  64,  71,  82,
        76,  91,  96, 109, 109, 109, 125, 123, 125, 143, 148, 151, 151,
       157, 167, 174, 183, 183, 193, 195, 199, 212, 216, 213, 229, 227,
       239, 251, 244, 254, 269, 268, 271, 276, 282, 295, 291])

In [6]:
X_1 = np.c_[np.ones((50, 1)), X]
X_1



array([[ 1.,  3.],
       [ 1.,  5.],
       [ 1.,  6.],
       [ 1.,  4.],
       [ 1., 11.],
       [ 1., 11.],
       [ 1., 10.],
       [ 1., 13.],
       [ 1., 15.],
       [ 1., 16.],
       [ 1., 20.],
       [ 1., 24.],
       [ 1., 27.],
       [ 1., 25.],
       [ 1., 30.],
       [ 1., 33.],
       [ 1., 36.],
       [ 1., 37.],
       [ 1., 36.],
       [ 1., 41.],
       [ 1., 42.],
       [ 1., 42.],
       [ 1., 47.],
       [ 1., 49.],
       [ 1., 50.],
       [ 1., 48.],
       [ 1., 50.],
       [ 1., 55.],
       [ 1., 59.],
       [ 1., 60.],
       [ 1., 59.],
       [ 1., 64.],
       [ 1., 64.],
       [ 1., 67.],
       [ 1., 70.],
       [ 1., 71.],
       [ 1., 71.],
       [ 1., 76.],
       [ 1., 76.],
       [ 1., 81.],
       [ 1., 84.],
       [ 1., 81.],
       [ 1., 83.],
       [ 1., 89.],
       [ 1., 90.],
       [ 1., 89.],
       [ 1., 90.],
       [ 1., 93.],
       [ 1., 99.],
       [ 1., 96.]])

In [7]:
best_W = np.linalg.inv(X_1.T.dot(X_1)).dot(X_1.T).dot(Y)
best_W

array([1.69807106, 2.99483445])

In [27]:
# from IPython.display import clear_output
# m = 0
# c = 0
# lr = 0.00001
# # y = m*+c
# error = sum((y - (m*X + c))**2)/len(Y)
# for n in range(200):
#     clear_output(wait=True)
#     # y = m*X+c
   
#     dm = 2/len(Y)*sum((Y-(m*X+c))*(-X))
#     dc = 2/len(Y)*sum((Y-(m*X+c))*(-1))
#     m=m-dm*lr
#     c=c-dc*lr
#     fig =plt.figure()
#     plt.scatter(x = X, y = Y)
#     plt.plot(X, m*X+c,"r")
#     plt.title(f"iter: {n}, error:{sum((Y - (m*X + c))**2)/len(Y)},m: {m}, c: {c}" )
#     plt.show()

In [11]:
dm

-38644.59430374436

In [12]:
dc

-582.1929269659714